from __future__ import annotations
import argparse
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from readiness.engine import load_snapshot,parse_gates,summarize
from readiness.authoritative import validate_release_evidence_artifact

def main()->int:
 parser=argparse.ArgumentParser(description="Fail-closed AISearch production readiness gate.")
 parser.add_argument("snapshot",nargs="?",default=str(ROOT/"data"/"snapshot.json"),help="Path to readiness snapshot JSON.")
 parser.add_argument("--release-evidence",help="Authoritative release-evidence JSON generated by platform/apps/api/scripts/release_evidence.py.")
 args=parser.parse_args()
 try:
  authoritative_validated=False
  if args.release_evidence:
   validate_release_evidence_artifact(Path(args.release_evidence).read_text(encoding="utf-8"),ROOT.parents[1]);authoritative_validated=True
  summary=summarize(parse_gates(load_snapshot(args.snapshot)),authoritative_validated)
 except (OSError,ValueError,TypeError) as exc:
  print("Decision: NO-GO");print(f"Validation error: {exc}");return 2
 print(f"Decision: {summary['decision']}");print(f"Blocking pass rate: {summary['blocking_gate_pass_rate']:.1%}");print(f"Verified pass rate: {summary['verified_pass_rate']:.1%}");print(f"Trust completion: {summary['trust_surface_completion']:.1%}");print(f"Blocking not PASS: {summary['blocking_not_pass']}")
 return 0 if summary["production_go"] else 2

if __name__=="__main__":raise SystemExit(main())
